modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Vazkii/Morph-o-Tool"

[[mods]]
modId="morphtool"
displayName="Morph-o-Tool"
version="${version}"
authors="Vazkii, MoreThanHidden"
description='''
The wrench to end all wrenches.
'''
[[dependencies.morphtool]]
    modId="autoreglib"
    mandatory=true
    versionRange="[1.5-36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.morphtool]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.42,)"
    ordering="AFTER"
    side="BOTH"